#Hugo configuration
title = "wqesasa"
baseURL = "https:\/\/qwedasd.asd.qwe"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
